import {
  User,
  Company,
  Plan,
  Subscription,
  Category,
  CostCenter,
  Client,
  Product,
  Revenue,
  Expense,
  Partner,
  Budget,
  OrganizationMember,
  OrganizationInvitation,
  BankAccount,
  RevenueCategory,
  ExpenseCategory,
} from '../../types';

/**
 * Fixtures estritas do MODO DE PRÉ-VISUALIZAÇÃO INTERNA.
 * Esses dados existem EXCLUSIVAMENTE em memória e NUNCA são gravados no Supabase.
 */

// 1. Usuário Mock do Preview
export const PREVIEW_USER: User = {
  id: 'preview-user-admin',
  name: 'Administrador NOX4',
  email: 'administrador@nox4.demonstracao',
  role: 'owner',
  status: 'active',
  created_at: new Date().toISOString(),
};

// 2. Organização / Empresa Mock do Preview
export const PREVIEW_COMPANY: Company = {
  id: 'preview-organization',
  name: 'Empresa Demonstração',
  document: '12.345.678/0001-90',
  cnpj: '12.345.678/0001-90',
  segment: 'Tecnologia & Serviços Financeiros',
  currency: 'BRL',
  created_at: '2026-01-01T00:00:00Z',
};

// 3. Plano e Assinatura Estritos do Preview (Req. 9)
export const PREVIEW_PLAN: Plan = {
  id: 'plan-preview-nox4',
  name: 'NOX4',
  description: 'Plano empresarial de alta performance e CFO digital integrado',
  max_organizations: 1, // CIAs incluídas: 1
  included_users: 3,    // Usuários incluídos: 3
  extra_user_price: 29.9, // Usuário adicional: R$ 29,90
  price: 249.0,
  active: true,
};

export const PREVIEW_SUBSCRIPTION: Subscription = {
  id: 'sub-preview-001',
  organization_id: 'preview-organization',
  plan_id: 'plan-preview-nox4',
  status: 'active', // Status: Ativo
  current_period_end: '2026-12-31T23:59:59Z',
  created_at: '2026-01-01T00:00:00Z',
  plan: PREVIEW_PLAN,
};

// 4. Membros da Equipe (5 usuários ativos para bater com os 5 usuários ativos do plano)
export const PREVIEW_MEMBERS: OrganizationMember[] = [
  {
    id: 'mem-1',
    organization_id: 'preview-organization',
    user_id: 'preview-user-admin',
    role: 'owner',
    user_name: 'Administrador NOX4',
    user_email: 'administrador@nox4.demonstracao',
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'mem-2',
    organization_id: 'preview-organization',
    user_id: 'preview-user-fin-1',
    role: 'finance',
    user_name: 'Mariana Financeira',
    user_email: 'mariana.financas@empresa.com.br',
    created_at: '2026-01-15T14:30:00Z',
  },
  {
    id: 'mem-3',
    organization_id: 'preview-organization',
    user_id: 'preview-user-fin-2',
    role: 'finance',
    user_name: 'Carlos Controladoria',
    user_email: 'carlos.control@empresa.com.br',
    created_at: '2026-02-01T09:15:00Z',
  },
  {
    id: 'mem-4',
    organization_id: 'preview-organization',
    user_id: 'preview-user-view-1',
    role: 'viewer',
    user_name: 'Beatriz Diretoria',
    user_email: 'beatriz.board@empresa.com.br',
    created_at: '2026-02-10T11:00:00Z',
  },
  {
    id: 'mem-5',
    organization_id: 'preview-organization',
    user_id: 'preview-user-view-2',
    role: 'viewer',
    user_name: 'Lucas Auditor',
    user_email: 'lucas.auditoria@empresa.com.br',
    created_at: '2026-02-20T16:45:00Z',
  },
];

// Convites pendentes de demonstração (não contabilizados em membros ativos)
export const PREVIEW_INVITATIONS: OrganizationInvitation[] = [
  {
    id: 'inv-preview-1',
    organization_id: 'preview-organization',
    email: 'roberto.consultor@externo.com',
    role: 'finance',
    name: 'Roberto Consultor',
    invited_by: 'Administrador NOX4',
    status: 'pending',
    created_at: '2026-02-25T10:00:00Z',
  },
];

// 5. Centros de Resultado / Custos
export const PREVIEW_COST_CENTERS: CostCenter[] = [
  {
    id: 'cc-1',
    company_id: 'preview-organization',
    name: 'Tecnologia & Produto',
    code: '1.01',
    type: 'operational',
    description: 'Desenvolvimento e infraestrutura de engenharia',
    active: true,
  },
  {
    id: 'cc-2',
    company_id: 'preview-organization',
    name: 'Comercial & Marketing',
    code: '1.02',
    type: 'commercial',
    description: 'Aquisição de clientes e canais de distribuição',
    active: true,
  },
  {
    id: 'cc-3',
    company_id: 'preview-organization',
    name: 'Administrativo & Finanças',
    code: '1.03',
    type: 'administrative',
    description: 'Gestão corporativa, governança e suporte',
    active: true,
  },
];

// 6. Categorias DRE e Financeiras
export const PREVIEW_CATEGORIES: Category[] = [
  {
    id: 'cat-rec-1',
    company_id: 'preview-organization',
    name: 'Receita de Software (SaaS)',
    type: 'REVENUE',
    code: '3.01.01',
    group: 'services',
    active: true,
  },
  {
    id: 'cat-rec-2',
    company_id: 'preview-organization',
    name: 'Consultoria Estratégica & Projetos',
    type: 'REVENUE',
    code: '3.01.02',
    group: 'services',
    active: true,
  },
  {
    id: 'cat-rec-3',
    company_id: 'preview-organization',
    name: 'Receitas Financeiras / Aplicações',
    type: 'FINANCIAL',
    code: '3.03.01',
    group: 'financial',
    active: true,
  },
  {
    id: 'cat-ded-1',
    company_id: 'preview-organization',
    name: 'Impostos s/ Faturamento (Simples / ISS)',
    type: 'TAX',
    code: '4.01.01',
    group: 'deductions',
    active: true,
  },
  {
    id: 'cat-cost-1',
    company_id: 'preview-organization',
    name: 'Infraestrutura Cloud & Servidores',
    type: 'VARIABLE_COST',
    code: '4.02.01',
    group: 'cost_of_services',
    active: true,
  },
  {
    id: 'cat-exp-adm-1',
    company_id: 'preview-organization',
    name: 'Folha de Pagamento & Salários',
    type: 'OPERATIONAL_EXPENSE',
    code: '5.01.01',
    group: 'administrative',
    active: true,
  },
  {
    id: 'cat-exp-com-1',
    company_id: 'preview-organization',
    name: 'Publicidade & Marketing Digital',
    type: 'OPERATIONAL_EXPENSE',
    code: '5.02.01',
    group: 'commercial',
    active: true,
  },
  {
    id: 'cat-exp-adm-2',
    company_id: 'preview-organization',
    name: 'Sede, Aluguel & Internet',
    type: 'OPERATIONAL_EXPENSE',
    code: '5.01.02',
    group: 'administrative',
    active: true,
  },
];

// 7. Clientes Mock
export const PREVIEW_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    company_id: 'preview-organization',
    name: 'Acme Corporation Brasil',
    document: '23.456.789/0001-12',
    email: 'financeiro@acmebrasil.com.br',
    phone: '(11) 3456-7890',
    status: 'ACTIVE',
    segment: 'Manufatura & Automação',
    contract_start_date: '2025-03-01',
    contract_value: 36000,
    mrr: 3000,
    created_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 'cli-2',
    company_id: 'preview-organization',
    name: 'Nexus Inteligência & Dados',
    document: '34.567.890/0001-23',
    email: 'contato@nexusdados.com.br',
    phone: '(21) 2233-4455',
    status: 'ACTIVE',
    segment: 'Fintech',
    contract_start_date: '2025-06-15',
    contract_value: 60000,
    mrr: 5000,
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: 'cli-3',
    company_id: 'preview-organization',
    name: 'Horizon Logística Integrada',
    document: '45.678.901/0001-34',
    email: 'contas@horizonlog.com.br',
    phone: '(31) 3344-5566',
    status: 'ACTIVE',
    segment: 'Logística',
    contract_start_date: '2025-08-01',
    contract_value: 48000,
    mrr: 4000,
    created_at: '2025-08-01T00:00:00Z',
  },
  {
    id: 'cli-4',
    company_id: 'preview-organization',
    name: 'Alpha Prime Consultoria',
    document: '56.789.012/0001-45',
    email: 'adm@alphaprime.com.br',
    phone: '(41) 3011-2233',
    status: 'PROSPECT',
    segment: 'Consultoria',
    contract_start_date: '2026-02-01',
    contract_value: 18000,
    mrr: 1500,
    created_at: '2026-02-01T00:00:00Z',
  },
];

// 8. Produtos e Serviços
export const PREVIEW_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    company_id: 'preview-organization',
    name: 'Plataforma NOX4 Enterprise (SaaS)',
    type: 'subscription',
    description: 'Assinatura anual de inteligência financeira e conciliação',
    price: 3500.0,
    cost_estimate: 350.0,
    is_recurring: true,
    active: true,
    cost_center_id: 'cc-1',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-2',
    company_id: 'preview-organization',
    name: 'Diagnóstico & Implantação de CFO Digital',
    type: 'service',
    description: 'Consultoria e estruturação de plano de contas e orçamento',
    price: 8500.0,
    cost_estimate: 1800.0,
    is_recurring: false,
    active: true,
    cost_center_id: 'cc-2',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-3',
    company_id: 'preview-organization',
    name: 'Treinamento de Controladoria & Equipes',
    type: 'consulting',
    description: 'Capacitação prática em análise de DRE e fluxo de caixa',
    price: 2400.0,
    cost_estimate: 400.0,
    is_recurring: false,
    active: true,
    cost_center_id: 'cc-3',
    created_at: '2026-01-01T00:00:00Z',
  },
];

// Helper para obter mês atual no formato YYYY-MM
const now = new Date();
const currentYear = now.getFullYear();
const currentMonthNumber = String(now.getMonth() + 1).padStart(2, '0');
export const PREVIEW_CURRENT_MONTH = `${currentYear}-${currentMonthNumber}`;

// 9. Receitas de Demonstração
export const PREVIEW_REVENUES: Revenue[] = [
  {
    id: 'rev-001',
    company_id: 'preview-organization',
    client_id: 'cli-1',
    product_id: 'prod-1',
    cost_center_id: 'cc-1',
    category_id: 'cat-rec-1',
    description: 'Assinatura NOX4 Enterprise - Acme Brasil',
    competence_date: `${PREVIEW_CURRENT_MONTH}-01`,
    due_date: `${PREVIEW_CURRENT_MONTH}-10`,
    received_date: `${PREVIEW_CURRENT_MONTH}-10`,
    payment_date: `${PREVIEW_CURRENT_MONTH}-10`,
    gross_amount: 15000.0,
    tax_amount: 900.0,
    net_amount: 14100.0,
    status: 'received',
    payment_method: 'pix',
    is_recurring: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rev-002',
    company_id: 'preview-organization',
    client_id: 'cli-2',
    product_id: 'prod-1',
    cost_center_id: 'cc-1',
    category_id: 'cat-rec-1',
    description: 'Assinatura NOX4 Enterprise - Nexus Inteligência',
    competence_date: `${PREVIEW_CURRENT_MONTH}-05`,
    due_date: `${PREVIEW_CURRENT_MONTH}-15`,
    received_date: `${PREVIEW_CURRENT_MONTH}-14`,
    payment_date: `${PREVIEW_CURRENT_MONTH}-14`,
    gross_amount: 18500.0,
    tax_amount: 1110.0,
    net_amount: 17390.0,
    status: 'received',
    payment_method: 'wire_transfer',
    is_recurring: true,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'rev-003',
    company_id: 'preview-organization',
    client_id: 'cli-3',
    product_id: 'prod-2',
    cost_center_id: 'cc-2',
    category_id: 'cat-rec-2',
    description: 'Consultoria de CFO Digital - Horizon Logística',
    competence_date: `${PREVIEW_CURRENT_MONTH}-10`,
    due_date: `${PREVIEW_CURRENT_MONTH}-25`,
    gross_amount: 12000.0,
    tax_amount: 720.0,
    net_amount: 11280.0,
    status: 'pending',
    payment_method: 'boleto',
    is_recurring: false,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'rev-004',
    company_id: 'preview-organization',
    client_id: 'cli-1',
    product_id: 'prod-3',
    cost_center_id: 'cc-3',
    category_id: 'cat-rec-2',
    description: 'Workshop de Governança Financeira',
    competence_date: `${PREVIEW_CURRENT_MONTH}-15`,
    due_date: `${PREVIEW_CURRENT_MONTH}-28`,
    gross_amount: 6800.0,
    tax_amount: 408.0,
    net_amount: 6392.0,
    status: 'pending',
    payment_method: 'pix',
    is_recurring: false,
    created_at: '2026-01-15T00:00:00Z',
  },
];

// 10. Despesas de Demonstração
export const PREVIEW_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    company_id: 'preview-organization',
    cost_center_id: 'cc-1',
    category_id: 'cat-cost-1',
    supplier: 'Amazon Web Services (AWS)',
    description: 'Hospedagem Cloud, Bancos e Kubernetes',
    competence_date: `${PREVIEW_CURRENT_MONTH}-01`,
    due_date: `${PREVIEW_CURRENT_MONTH}-05`,
    paid_date: `${PREVIEW_CURRENT_MONTH}-05`,
    payment_date: `${PREVIEW_CURRENT_MONTH}-05`,
    amount: 3200.0,
    cost_nature: 'VARIABLE',
    status: 'paid',
    payment_method: 'credit_card',
    is_recurring: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'exp-002',
    company_id: 'preview-organization',
    cost_center_id: 'cc-3',
    category_id: 'cat-exp-adm-1',
    supplier: 'Folha de Pagamento & Encargos',
    description: 'Salários da equipe operacional e técnica',
    competence_date: `${PREVIEW_CURRENT_MONTH}-05`,
    due_date: `${PREVIEW_CURRENT_MONTH}-05`,
    paid_date: `${PREVIEW_CURRENT_MONTH}-05`,
    payment_date: `${PREVIEW_CURRENT_MONTH}-05`,
    amount: 16500.0,
    cost_nature: 'FIXED',
    status: 'paid',
    payment_method: 'wire_transfer',
    is_recurring: true,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'exp-003',
    company_id: 'preview-organization',
    cost_center_id: 'cc-2',
    category_id: 'cat-exp-com-1',
    supplier: 'Google Ads & LinkedIn Ads',
    description: 'Campanhas de captação B2B',
    competence_date: `${PREVIEW_CURRENT_MONTH}-10`,
    due_date: `${PREVIEW_CURRENT_MONTH}-20`,
    amount: 4500.0,
    cost_nature: 'VARIABLE',
    status: 'pending',
    payment_method: 'credit_card',
    is_recurring: true,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'exp-004',
    company_id: 'preview-organization',
    cost_center_id: 'cc-3',
    category_id: 'cat-exp-adm-2',
    supplier: 'Horizon Office & Condomínio',
    description: 'Locação do escritório e infraestrutura física',
    competence_date: `${PREVIEW_CURRENT_MONTH}-01`,
    due_date: `${PREVIEW_CURRENT_MONTH}-10`,
    paid_date: `${PREVIEW_CURRENT_MONTH}-10`,
    payment_date: `${PREVIEW_CURRENT_MONTH}-10`,
    amount: 3800.0,
    cost_nature: 'FIXED',
    status: 'paid',
    payment_method: 'boleto',
    is_recurring: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'exp-005',
    company_id: 'preview-organization',
    cost_center_id: 'cc-3',
    category_id: 'cat-ded-1',
    supplier: 'Receita Federal do Brasil',
    description: 'DAS - Simples Nacional Competência Anterior',
    competence_date: `${PREVIEW_CURRENT_MONTH}-15`,
    due_date: `${PREVIEW_CURRENT_MONTH}-20`,
    amount: 2850.0,
    cost_nature: 'VARIABLE',
    status: 'pending',
    payment_method: 'boleto',
    is_recurring: true,
    created_at: '2026-01-15T00:00:00Z',
  },
];

// 11. Sócios & Governança Patrimonial
export const PREVIEW_PARTNERS: Partner[] = [
  {
    id: 'part-1',
    company_id: 'preview-organization',
    name: 'Guilherme Sócio Fundador',
    document: '123.456.789-00',
    ownership_percentage: 60,
    equity_percentage: 60,
    prolabore_amount: 14000,
    role: 'Diretor Geral (CEO)',
    active: true,
    email: 'guilherme@nox4.demonstracao',
    phone: '(11) 98765-4321',
  },
  {
    id: 'part-2',
    company_id: 'preview-organization',
    name: 'Patrícia Sócia Operações',
    document: '234.567.890-11',
    ownership_percentage: 40,
    equity_percentage: 40,
    prolabore_amount: 11000,
    role: 'Diretora Financeira (CFO)',
    active: true,
    email: 'patricia@nox4.demonstracao',
    phone: '(11) 97654-3210',
  },
];

// 12. Contas Bancárias
export const PREVIEW_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'bank-1',
    company_id: 'preview-organization',
    name: 'Conta Corrente Principal',
    bank: 'Banco Itaú BBA',
    account_type: 'checking',
    account_number: '12345-6',
    opening_balance: 148500.0,
    current_balance: 148500.0,
    active: true,
  },
  {
    id: 'bank-2',
    company_id: 'preview-organization',
    name: 'Conta Investimento BTG',
    bank: 'BTG Pactual Empresas',
    account_type: 'investment',
    account_number: '98765-4',
    opening_balance: 62400.0,
    current_balance: 62400.0,
    active: true,
  },
];

// 13. Orçamentos
export const PREVIEW_BUDGETS: Budget[] = [
  {
    id: 'bgt-1',
    company_id: 'preview-organization',
    name: 'Orçamento Anual 2026',
    reference_month: PREVIEW_CURRENT_MONTH,
    status: 'active',
    items: [
      {
        id: 'bgt-item-1',
        budget_id: 'bgt-1',
        category_id: 'cat-rec-1',
        category_name: 'Receita de Software (SaaS)',
        group: 'revenue',
        type: 'revenue',
        planned_amount: 35000,
        actual_amount: 33500,
      },
      {
        id: 'bgt-item-2',
        budget_id: 'bgt-1',
        category_id: 'cat-cost-1',
        category_name: 'Infraestrutura Cloud & Servidores',
        group: 'cost_of_services',
        type: 'expense',
        planned_amount: 3500,
        actual_amount: 3200,
      },
      {
        id: 'bgt-item-3',
        budget_id: 'bgt-1',
        category_id: 'cat-exp-adm-1',
        category_name: 'Folha de Pagamento & Salários',
        group: 'administrative',
        type: 'expense',
        planned_amount: 17000,
        actual_amount: 16500,
      },
    ],
  },
];

// Categorias segregadas para o motor DRE
export const PREVIEW_REVENUE_CATEGORIES: RevenueCategory[] = [
  {
    id: 'cat-rec-1',
    company_id: 'preview-organization',
    name: 'Receita de Software (SaaS)',
    type: 'recurring',
    active: true,
  },
  {
    id: 'cat-rec-2',
    company_id: 'preview-organization',
    name: 'Consultoria Financeira Especializada',
    type: 'services',
    active: true,
  },
  {
    id: 'cat-rec-3',
    company_id: 'preview-organization',
    name: 'Treinamento Corporativo',
    type: 'non_recurring',
    active: true,
  },
];

export const PREVIEW_EXPENSE_CATEGORIES: ExpenseCategory[] = [
  {
    id: 'cat-cost-1',
    company_id: 'preview-organization',
    name: 'Infraestrutura Cloud & Servidores',
    group: 'cost_of_services',
    type: 'variable',
    active: true,
  },
  {
    id: 'cat-cost-2',
    company_id: 'preview-organization',
    name: 'Softwares & Ferramentas Operacionais',
    group: 'cost_of_services',
    type: 'fixed',
    active: true,
  },
  {
    id: 'cat-exp-adm-1',
    company_id: 'preview-organization',
    name: 'Folha de Pagamento & Salários',
    group: 'administrative',
    type: 'fixed',
    active: true,
  },
  {
    id: 'cat-exp-adm-2',
    company_id: 'preview-organization',
    name: 'Contabilidade & Assessoria Jurídica',
    group: 'administrative',
    type: 'fixed',
    active: true,
  },
  {
    id: 'cat-exp-com-1',
    company_id: 'preview-organization',
    name: 'Marketing Digital & Anúncios',
    group: 'commercial',
    type: 'variable',
    active: true,
  },
];
